import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import initTranslations from '@/utils/i18n';
import { TranslationsProvider } from '@/providers/TranslationProvider';
import Tailwind from 'primereact/passthrough/tailwind';
import SideMenu from '@/components/side-menu/SideMenu';
import BaseView from '@/components/base/view/BaseView';
import Header from '@/components/header/Header';
import Providers from '@/providers/Providers';
import { StyleProvider } from '@/providers/StyleProvider';
import '../globals.css';
import LoadingProvider from '@/providers/LoadingProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(
  props: Readonly<{
    children: ReactNode;
    params: Promise<{ locale: string }>;
  }>,
) {
  const { params, children } = props;

  const { locale } = await params;
  const { resources } = await initTranslations({ locale });

  return (
    <html lang={locale} className={'w-full !bg-black relative'}>
      <body className={`${geistSans.variable} ${geistMono.variable} w-full bg-slate-700 antialiased`}>
        <StyleProvider>
          <Providers>
            <TranslationsProvider locale={locale} resources={resources}>
              <LoadingProvider/>
              <Header />
              <BaseView className={'w-full flex-row'}>
                <SideMenu />
                {children}
              </BaseView>
            </TranslationsProvider>
          </Providers>
        </StyleProvider>
      </body>
    </html>
  );
}
