import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import initTranslations from '@/utils/i18n';
import { TranslationsProvider } from '@/providers/TranslationProvider';
import '../globals.css';
import { PrimeReactProvider } from 'primereact/api';
import Tailwind from 'primereact/passthrough/tailwind';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(
  props: Readonly<{
    children: ReactNode;
    params: Promise<{ locale: string }>;
  }>,
) {
  const { params, children } = props;

  const { locale } = await params;
  const { resources } = await initTranslations({ locale });

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} bg-slate-700 antialiased`}>
        <TranslationsProvider locale={locale} resources={resources}>
          <PrimeReactProvider value={{ pt: Tailwind }}>{children}</PrimeReactProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
